In [1]:
import numpy as np

2.	Найти сумму и произведение матриц 

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A, B = np.array(((1, -2), (3, 0))), np.array(((4, -1), (0, 5)))

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 3A-2B+4C

$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [5]:
A, B, C = np.array(((1, 7), (3, -6))), np.array(((0, 5), (2, -1))), np.array(((2, -4), (1, 1)))

In [6]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица A. Вычислить $AA^{Т}$ и $A^{T}A$

 $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$

In [7]:
A = np.array(((4, 1), (5, -2), (2, 3)))

In [8]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

5.	Вычислить определитель

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

In [10]:
np.linalg.det(np.array(((np.sin(1.32123), -np.cos(1.32123)), (np.cos(1.32123), np.sin(1.32123)))))

1.0

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$

In [11]:
np.linalg.det(np.array(((4, 2, 3), (0, 5, 1), (0, 0, 9))))

180.0

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

In [12]:
np.linalg.det(np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9))))

6.66133814775094e-16

7.	Доказать, что матрица вырожденная

$A=\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$

In [13]:
A = np.array(((-2,7,-3), (4, -14, 6), (-3, 7, 13)))

In [14]:
np.linalg.det(A)

0.0

    Матрица - вырожденная.

8. Найти ранг матрицы:

$A=\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [15]:
np.linalg.matrix_rank(np.array(((1, 2, 3), (1, 1, 1), (2, 3, 4))))

2

$A=\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [16]:
np.linalg.matrix_rank(np.array(((0, 0, 2, 1), (0, 0, 2, 2), (0, 0, 4, 3), (2, 3, 5, 6))))

3

__Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.__

In [17]:
def dot(A, B):
    if A.shape[1] != B.shape[0]:
        print('Неправильные размерности матриц!')
        return 0
    t = A.shape[1]
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            temp = 0
            for k in range(t):
                temp += A[i, k] * B[k, j]
            C[i, j] = temp
    return C
                

In [18]:
A, B = np.array(((1, -2), (3, 0))), np.array(((4, -1), (0, 5)))

In [19]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

In [20]:
dot(A, B)

array([[  4., -11.],
       [ 12.,  -3.]])